# Generated by Django 5.1.7 on 2025-04-23 01:54

import api.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('type_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_pay', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_payment', models.DateTimeField(blank=True, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=50)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_payment',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id_truck', models.AutoField(primary_key=True, serialize=False)),
                ('number_truck', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(db_default=True, default=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.person')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_user',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='id_company',
            field=models.ForeignKey(blank=True, db_column='id_company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='api.company'),
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id_operator', models.AutoField(primary_key=True, serialize=False)),
                ('number_licence', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('n_children', models.IntegerField(blank=True, null=True)),
                ('size_t_shift', models.CharField(blank=True, max_length=20, null=True)),
                ('name_t_shift', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=api.utils.upload_operator_file)),
                ('license_front', models.ImageField(blank=True, null=True, upload_to=api.utils.upload_operator_file)),
                ('license_back', models.ImageField(blank=True, null=True, upload_to=api.utils.upload_operator_file)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('person', models.OneToOneField(db_column='id_person', on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.operator')),
            ],
            options={
                'db_table': 'api_assign',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
                ('expense', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('payStatus', models.SmallIntegerField(blank=True, null=True)),
                ('evidence', models.URLField(blank=True, null=True)),
                ('state_usa', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, null=True)),
                ('assign', models.ManyToManyField(db_column='id_assign', related_name='assigned_operators', through='api.Assign', to='api.operator')),
                ('id_company', models.ForeignKey(blank=True, db_column='id_company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.company')),
                ('job', models.ForeignKey(db_column='id_job', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.job')),
                ('person', models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='AssignTool',
            fields=[
                ('id_assign_tool', models.AutoField(db_column='id_assign_tool', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('key', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='assign_tool', to='api.order')),
            ],
        ),
        migrations.AddField(
            model_name='assign',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.order'),
        ),
        migrations.AddField(
            model_name='assign',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='api.payment'),
        ),
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id_son', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('operator', models.ForeignKey(db_column='id_operator', on_delete=django.db.models.deletion.CASCADE, related_name='sons', to='api.operator')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(db_column='id_tool', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('job', models.ForeignKey(db_column='id_job', on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='api.job')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tool',
            field=models.ManyToManyField(db_column='id_tool', related_name='order_tools', through='api.AssignTool', to='api.tool'),
        ),
        migrations.AddField(
            model_name='assigntool',
            name='id_tool',
            field=models.ForeignKey(db_column='id_tool', on_delete=django.db.models.deletion.CASCADE, related_name='assign_tool', to='api.tool'),
        ),
        migrations.CreateModel(
            name='CostFuel',
            fields=[
                ('id_fuel', models.AutoField(primary_key=True, serialize=False)),
                ('cost_fuel', models.FloatField()),
                ('cost_gl', models.FloatField()),
                ('fuel_qty', models.FloatField()),
                ('distance', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_fuels', to='api.order')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_fuels', to='api.truck')),
            ],
        ),
        migrations.CreateModel(
            name='AssignAudit',
            fields=[
                ('id', models.AutoField(db_column='id_assign_audit', primary_key=True, serialize=False)),
                ('old_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('new_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('old_rol', models.CharField(blank=True, max_length=100, null=True)),
                ('new_rol', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('assign', models.ForeignKey(db_column='id_assign', help_text='Assignment to which this audit record belongs', on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='api.assign')),
                ('new_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records_as_new_operator', to='api.operator')),
                ('old_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records_as_old_operator', to='api.operator')),
                ('new_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records_as_new_order', to='api.order')),
                ('old_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records_as_old_order', to='api.order')),
                ('new_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records_as_new_payment', to='api.payment')),
                ('old_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records_as_old_payment', to='api.payment')),
                ('new_truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records_as_new_truck', to='api.truck')),
                ('old_truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records_as_old_truck', to='api.truck')),
            ],
            options={
                'db_table': 'api_assign_audit',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.AddField(
            model_name='assign',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.truck'),
        ),
        migrations.CreateModel(
            name='WorkCost',
            fields=[
                ('id_workCost', models.AutoField(db_column='id_workCost', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('type', models.CharField(max_length=10)),
                ('id_order', models.ForeignKey(blank=True, db_column='id_order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkCost', to='api.order')),
            ],
        ),
    ]
