# Generated by Django 5.1.7 on 2025-04-04 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('license', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('cell_phone', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.BigIntegerField(blank=True, null=True)),
                ('type_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id_truck', models.AutoField(primary_key=True, serialize=False)),
                ('number_truck', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(db_default=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.person')),
                ('id_operator', models.AutoField(primary_key=True, serialize=False)),
                ('number_licence', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('n_children', models.IntegerField(blank=True, null=True)),
                ('size_t_shift', models.CharField(blank=True, max_length=20, null=True)),
                ('name_t_shift', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('api.person',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
                ('expense', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('payStatus', models.SmallIntegerField(blank=True, null=True)),
                ('state_usa', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, null=True)),
                ('job', models.ForeignKey(db_column='id_job', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.job')),
                ('person', models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='AssignTool',
            fields=[
                ('id_assign_tool', models.AutoField(db_column='id_assign_tool', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('id_order', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='assign_tool', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(db_column='id_tool', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('job', models.ForeignKey(db_column='id_job', on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='api.job')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tool',
            field=models.ManyToManyField(db_column='id_tool', related_name='order_tools', through='api.AssignTool', to='api.tool'),
        ),
        migrations.AddField(
            model_name='assigntool',
            name='id_tool',
            field=models.ForeignKey(db_column='id_tool', on_delete=django.db.models.deletion.CASCADE, related_name='assign_tool', to='api.tool'),
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.order')),
                ('truck', models.ForeignKey(blank=True, db_column='id_truck', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.truck')),
                ('operator', models.ForeignKey(db_column='id_operator', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.operator')),
            ],
            options={
                'unique_together': {('operator', 'order', 'truck')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='assign',
            field=models.ManyToManyField(db_column='id_assign', related_name='assigned_operators', through='api.Assign', to='api.operator'),
        ),
    ]
