# Generated by Django 5.0 on 2025-05-05 19:57

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatch_ticket',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=api.utils._upload_dispatch_file),
        ),
        migrations.AlterField(
            model_name='order',
            name='evidence',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=api.utils.upload_evidence_file),
        ),
    ]
