# Generated by Django 5.0 on 2025-04-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='id_pay',
            new_name='payment',
        ),
    ]
