# Generated by Django 5.1.7 on 2025-03-23 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='operator',
            field=models.ForeignKey(db_column='id_operator', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.operator'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='order',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.order'),
        ),
    ]
