# Generated by Django 5.0 on 2025-05-14 19:36

import api.utils.s3utils
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="dispatch_ticket",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to=api.utils.s3utils.upload_dispatch_file,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="evidence",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to=api.utils.s3utils.upload_evidence_file,
            ),
        ),
    ]
