# Generated by Django 5.1.7 on 2025-05-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.BooleanField(db_column='ACTIVE', default=True),
        ),
    ]
