# Generated by Django 5.1.7 on 2025-04-04 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.person')),
                ('id_operator', models.AutoField(primary_key=True, serialize=False)),
                ('number_licence', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('n_children', models.IntegerField(blank=True, null=True)),
                ('size_t_shift', models.CharField(blank=True, max_length=20, null=True)),
                ('name_t_shift', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('api.person',),
        ),
        migrations.AddField(
            model_name='order',
            name='job',
            field=models.ForeignKey(db_column='id_job', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.job'),
        ),
        migrations.AddField(
            model_name='order',
            name='person',
            field=models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.person'),
        ),
        migrations.AddField(
            model_name='company',
            name='id_order',
            field=models.ForeignKey(blank=True, db_column='id_order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='api.order'),
        ),
        migrations.AddField(
            model_name='assign',
            name='order',
            field=models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.order'),
        ),
        migrations.AddField(
            model_name='tool',
            name='job',
            field=models.ForeignKey(db_column='id_job', on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='api.job'),
        ),
        migrations.AddField(
            model_name='assign',
            name='truck',
            field=models.ForeignKey(blank=True, db_column='id_truck', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.truck'),
        ),
        migrations.AddField(
            model_name='order',
            name='assign',
            field=models.ManyToManyField(db_column='id_assign', related_name='assigned_operators', through='api.Assign', to='api.operator'),
        ),
        migrations.AddField(
            model_name='assign',
            name='operator',
            field=models.ForeignKey(db_column='id_operator', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.operator'),
        ),
        migrations.AlterUniqueTogether(
            name='assign',
            unique_together={('operator', 'order', 'truck')},
        ),
    ]
