# Generated by Django 5.1.7 on 2025-04-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='fist_name',
        ),
    ]
