# Generated by Django 5.0 on 2025-04-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
