# Generated by Django 5.0 on 2025-05-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerFactory",
            fields=[
                ("id_factory", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="customer_factory",
            field=models.ForeignKey(
                blank=True,
                db_column="id_factory",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="api.customerfactory",
            ),
        ),
    ]
