# Generated by Django 5.1.7 on 2025-04-16 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='WorkCost',
            fields=[
                ('id_workCost', models.AutoField(db_column='id_workCost', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('type', models.CharField(max_length=10)),
                ('id_order', models.ForeignKey(blank=True, db_column='id_order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkCost', to='api.order')),
            ],
        ),
    ]
