# Generated by Django 5.1.7 on 2025-03-23 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id_operator', models.AutoField(primary_key=True, serialize=False)),
                ('number_licence', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('n_children', models.IntegerField(blank=True, null=True)),
                ('size_t_shift', models.CharField(blank=True, max_length=20, null=True)),
                ('name_t_shift', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('id_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('job', models.ForeignKey(db_column='id_job', on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='api.job')),
            ],
        ),
    ]
