# Generated by Django 5.0 on 2025-04-05 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Value',
            new_name='value',
        ),
    ]
