# Generated by Django 5.0 on 2025-04-25 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'api_company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='job',
            name='id_company',
            field=models.ForeignKey(blank=True, db_column='id_company', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='id_company',
            field=models.ForeignKey(blank=True, db_column='id_company', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='api.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_company',
            field=models.ForeignKey(db_column='id_company', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='id_company',
            field=models.ForeignKey(blank=True, db_column='id_company', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='id_company',
            field=models.ForeignKey(blank=True, db_column='id_company', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='api.company'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='company',
            table='api_company',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id_subscription', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscription'),
        ),
    ]
