# Generated by Django 5.1.7 on 2025-05-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfactory',
            name='state',
            field=models.BooleanField(db_column='ACTIVE', default=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
