# Generated by Django 5.0 on 2025-05-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customerfactory_order_customer_factory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
