# Generated by Django 5.1.7 on 2025-03-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_assign_operator_alter_assign_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='order',
            field=models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.order'),
        ),
    ]
