# Generated by Django 5.0 on 2025-04-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plan_alter_company_options_job_id_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='id_user',
        ),
    ]
