# Generated by Django 5.0 on 2025-05-14 19:37

import api.utils.s3utils
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_order_dispatch_ticket_alter_order_evidence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operator",
            name="license_back",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to=api.utils.s3utils.upload_operator_license_back,
            ),
        ),
        migrations.AlterField(
            model_name="operator",
            name="license_front",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to=api.utils.s3utils.upload_operator_license_front,
            ),
        ),
        migrations.AlterField(
            model_name="operator",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to=api.utils.s3utils.upload_operator_photo,
            ),
        ),
    ]
