# Generated by Django 5.0 on 2025-04-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id_rol',
        ),
    ]
