# Generated by Django 5.0 on 2025-04-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_truck_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='additional_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
