# Generated by Django 5.1.7 on 2025-03-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_truck_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
