# Generated by Django 5.1.7 on 2025-04-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_person_fist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='cell_phone',
            new_name='phone',
        ),
    ]
