# Generated by Django 5.0 on 2025-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customerfactory_state_alter_truck_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operator",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("freelance", "Freelance"),
                ],
                default="active",
                max_length=50,
                null=True,
            ),
        ),
    ]
