# Generated by Django 5.1.7 on 2025-05-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfactory',
            name='state',
            field=models.BooleanField(db_column='ACTIVE', default=True),
        ),
    ]
