# Generated by Django 5.0 on 2025-04-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_truck_category_workcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostFuel',
            fields=[
                ('id_fuel', models.AutoField(primary_key=True, serialize=False)),
                ('cost_fuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_gl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('identifier_1', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_fuels', to='api.order')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_fuels', to='api.truck')),
            ],
        ),
    ]
