# Generated by Django 5.1.7 on 2025-04-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_cell_phone_person_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
