# Generated by Django 5.1.7 on 2025-04-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_truck_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTool',
            fields=[
                ('id_assign_tool', models.AutoField(db_column='id_assign_tool', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('id_order', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='assign_tool', to='api.order')),
                ('id_tool', models.ForeignKey(db_column='id_tool', on_delete=django.db.models.deletion.CASCADE, related_name='assign_tool', to='api.tool')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tool',
            field=models.ManyToManyField(db_column='id_tool', related_name='order_tools', through='api.AssignTool', to='api.tool'),
        ),
    ]
