# Generated by Django 5.1.7 on 2025-03-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_truck_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assign',
        ),
        migrations.AlterField(
            model_name='order',
            name='payStatus',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
