# Generated by Django 5.0 on 2025-04-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_costfuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costfuel',
            name='identifier_1',
        ),
    ]
