# Generated by Django 5.0 on 2025-05-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_operator_license_back_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="operator",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("code__isnull", False), models.Q(("code", ""), _negated=True)
                ),
                fields=("code",),
                name="unique_non_empty_operator_code",
            ),
        ),
    ]
