# Generated by Django 5.0 on 2025-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assign_additional_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
