# Generated by Django 5.1.7 on 2025-03-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_assign_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id_truck', models.AutoField(primary_key=True, serialize=False)),
                ('number_truck', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='assign',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assign',
            name='truck',
            field=models.ForeignKey(blank=True, db_column='id_truck', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.truck'),
        ),
        migrations.AlterUniqueTogether(
            name='assign',
            unique_together={('operator', 'order', 'truck')},
        ),
    ]
