# Generated by Django 5.0 on 2025-05-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_operator_unique_non_empty_operator_code"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="operator",
            name="unique_non_empty_operator_code",
        ),
        migrations.AlterField(
            model_name="operator",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
