# Generated by Django 5.1.7 on 2025-04-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assigntool_order_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.AutoField(db_column='id_tool', primary_key=True, serialize=False),
        ),
    ]
