# Generated by Django 5.1.7 on 2025-03-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_order_assign_alter_order_paystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assign',
            field=models.ManyToManyField(db_column='id_assign', related_name='assigned_operators', through='api.Assign', to='api.operator'),
        ),
    ]
