# Generated by Django 5.0 on 2025-04-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_costfuel_identifier_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='costfuel',
            name='distance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costfuel',
            name='cost_fuel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='costfuel',
            name='cost_gl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='costfuel',
            name='fuel_qty',
            field=models.FloatField(),
        ),
    ]
