# Generated by Django 5.1.7 on 2025-04-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_fist_name_person_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='evidence',
            field=models.URLField(blank=True, null=True),
        ),
    ]
