# Generated by Django 5.0 on 2025-04-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_costfuel_distance_alter_costfuel_cost_fuel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigntool',
            old_name='id_order',
            new_name='key',
        ),
    ]
